import { motion } from "framer-motion";
import Head from "next/head";
import React from "react";

import SeasonFeed from "../../components/SeasonPage/SeasonFeed";

type Props = {};

function SeasonPage({}: Props) {
  return (
    <motion.div
      initial={{ opacity: 0 }}
      whileInView={{ opacity: 1 }}
      viewport={{ once: true }}
    >
      <Head>
        <title>Netflix Clone</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link
          rel="icon"
          href="https://www.designbust.com/download/1037/png/netflix_logo_png_transparet512.png"
        />
      </Head>
      <SeasonFeed />
    </motion.div>
  );
}

export default SeasonPage;
