import { motion } from "framer-motion";
import { getSession } from "next-auth/react";
import Head from "next/head";
import FavoriteFeed from "../components/FavoriteFeed";

import Footer from "../components/Footer";
import Navbar from "../components/Navbar";
import SignIn from "../components/SignIn";

type Props = {
  session: any;
};

function Favorite({ session }: Props) {
  if (!session) return <SignIn />;

  return (
    <motion.div
      initial={{ opacity: 0 }}
      whileInView={{ opacity: 1 }}
      viewport={{ once: true }}
    >
      <Head>
        <title>Netflix Clone</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link
          rel="icon"
          href="https://www.designbust.com/download/1037/png/netflix_logo_png_transparet512.png"
        />
      </Head>
      <Navbar />
      <FavoriteFeed session={session} />
      <Footer />
    </motion.div>
  );
}

export default Favorite;

export const getServerSideProps = async (context: any) => {
  const session = await getSession(context);

  return {
    props: {
      session: session,
    },
  };
};
