import { motion } from "framer-motion";
import { getSession } from "next-auth/react";
import Head from "next/head";

import Footer from "../components/Footer";
import HomeBanner from "../components/HomeBanner";
import Navbar from "../components/Navbar";
import Row from "../components/Row";
import SignIn from "../components/SignIn";
import { Movie } from "../typings";
import requests from "../utils/requests";

type Props = {
  netflixOriginals: Movie[];
  trendingNow: Movie[];
  topRated: Movie[];
  actionMovies: Movie[];
  comedyMovies: Movie[];
  horrorMovies: Movie[];
  romanceMovies: Movie[];
  documentaries: Movie[];
  session: any;
};

export default function Home({
  netflixOriginals,
  trendingNow,
  topRated,
  actionMovies,
  comedyMovies,
  horrorMovies,
  romanceMovies,
  documentaries,
  session,
}: Props) {
  if (!session) return <SignIn />;

  return (
    <motion.div
      initial={{ opacity: 0 }}
      whileInView={{ opacity: 1 }}
      viewport={{ once: true }}
    >
      <Head>
        <title>Netflix Clone</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link
          rel="icon"
          href="https://www.designbust.com/download/1037/png/netflix_logo_png_transparet512.png"
        />
      </Head>
      <Navbar />
      <main className="relative pl-4 pb-24 lg:space-y-24">
        <HomeBanner netflixOriginals={netflixOriginals} />
        <section className="md:space-y-16">
          <Row title="Trending Now" movies={trendingNow} isDetails={false} />
          <Row title="Top Rated" movies={topRated} isDetails={false} />
          <Row
            title="Action Thrillers"
            movies={actionMovies}
            isDetails={false}
          />
          <Row title="Comedies" movies={comedyMovies} isDetails={false} />
          <Row title="Scary Movies" movies={horrorMovies} isDetails={false} />
          <Row
            title="Romance Movies"
            movies={romanceMovies}
            isDetails={false}
          />
          <Row title="Documentaries" movies={documentaries} isDetails={false} />
        </section>
      </main>
      <Footer />
    </motion.div>
  );
}

export const getServerSideProps = async (context: any) => {
  const session = await getSession(context);
  const [
    netflixOriginals,
    trendingNow,
    topRated,
    actionMovies,
    comedyMovies,
    horrorMovies,
    romanceMovies,
    documentaries,
  ] = await Promise.all([
    fetch(requests.fetchNetflixOriginals).then((res) => res.json()),
    fetch(requests.fetchTrending).then((res) => res.json()),
    fetch(requests.fetchTopRated).then((res) => res.json()),
    fetch(requests.fetchActionMovies).then((res) => res.json()),
    fetch(requests.fetchComedyMovies).then((res) => res.json()),
    fetch(requests.fetchHorrorMovies).then((res) => res.json()),
    fetch(requests.fetchRomanceMovies).then((res) => res.json()),
    fetch(requests.fetchDocumentaries).then((res) => res.json()),
  ]);

  return {
    props: {
      netflixOriginals: netflixOriginals.results,
      trendingNow: trendingNow.results,
      topRated: topRated.results,
      actionMovies: actionMovies.results,
      comedyMovies: comedyMovies.results,
      horrorMovies: horrorMovies.results,
      romanceMovies: romanceMovies.results,
      documentaries: documentaries.results,
      session: session,
    },
  };
};
